import sys
import shutil
import os
import subprocess
from pathlib import Path
from CIScripts import mod_info
from CIScripts import utils
from CIScripts import papyrus_compiler
from CIScripts import readme_formatter

def StarfieldSetup():
    shutil.move("Data/Starfield.esp", "Data/" + mod_info.config.modName + ".esp")
    os.remove("Data/Fallout4.esp")
    os.remove("Data/Skyrim.esp")
    shutil.rmtree("Data/SEQ/")
    shutil.move("Data/Scripts/" + mod_info.config.modShortName + "/", "Data/Scripts/Source/" + mod_info.config.modShortName + "/")
    
    # Create junction to the script folder for the official VSCode papyrus extension 
    scriptsPath = "./Data/Scripts/Source/" + mod_info.config.modShortName
    junction  = mod_info.config.gamePath + "/Data/Scripts/Source/" + mod_info.config.modShortName
    subprocess.run(f'mklink /J "{junction}" "{scriptsPath}"', shell=True)

def Fallout4Setup():
    shutil.move("Data/Fallout4.esp", "Data/" + mod_info.config.modName + ".esp")
    os.remove("Data/Starfield.esp")
    os.remove("Data/Skyrim.esp")
    shutil.rmtree("Data/SEQ/")
    shutil.move("Data/Scripts/" + mod_info.config.modShortName + "/", "Data/Scripts/Source/User/" + mod_info.config.modShortName + "/")

def FlattenNamespaces():
    root = Path("./Data/Source/Scripts")
    for src in list(root.rglob("*")):
        if not src.is_file() or src.parent == root:
            continue
        new_name = "_".join(src.relative_to(root).parts)
        shutil.move(src, root / new_name)
    shutil.rmtree("./Data/Source/Scripts/" + mod_info.config.modShortName + "/")

def SkyrimSetup():
    shutil.move("Data/Skyrim.esp", "Data/" + mod_info.config.modName + ".esp")
    os.remove("Data/Starfield.esp")
    os.remove("Data/Fallout4.esp")
    shutil.move("Data/Scripts/" + mod_info.config.modShortName + "/", "Data/Source/Scripts/" + mod_info.config.modShortName + "/")
    os.remove(mod_info.config.modName + "Debug.ppj")
    os.remove(mod_info.config.modName + "Release.ppj")
    FlattenNamespaces()

def main():   
    match utils.Game(sys.argv[1]):
        case utils.Game.STARFIELD:
            StarfieldSetup()
        case utils.Game.FALLOUT4:
            Fallout4Setup()
        case utils.Game.SKYRIM:
            SkyrimSetup()
        case _:
            print("CONFIGURATION ERROR")
    papyrus_compiler.FillTemplates(papyrus_compiler.CompileMode.DEFAULT)

    #Patch .esp
    with open("./Data/" + mod_info.config.modName + ".esp", "rb") as file:
        patchedFile = file.read()
        patchedFile = patchedFile.replace(b"\0ZEC_", b"\0" + mod_info.config.modShortName.encode() + b"_")
        patchedFile = patchedFile.replace(b"\0ZEC:", b"\0" + mod_info.config.modShortName.encode() + b":")
    with open("./Data/" + mod_info.config.modName + ".esp", "wb") as file:
        file.write(patchedFile)

    #Generate readme
    readme_formatter.FormatReadmeFile("./")
    readme_formatter.UpdateRepositoryReadme("./")

    #Setup MO2
    if len(sys.argv) > 2:
        mo2InstancePath = sys.argv[2] + mod_info.config.mo2InstanceName
        junctionName = mod_info.config.modName + "WIP"
        junction = os.fspath(mo2InstancePath + "/mods/" + junctionName)
        target = os.fspath("./Data")
        subprocess.run(f'mklink /J "{junction}" "{target}"', shell=True)

        if os.path.isdir(mo2InstancePath + "/profiles/ZZZ_Dev/"):
            mo2ProfilePath = mo2InstancePath + "/profiles/ZZZ_" + mod_info.config.modName +"/"
            shutil.copytree(mo2InstancePath + "/profiles/ZZZ_Dev/", mo2ProfilePath)

            with open(mo2ProfilePath + "loadorder.txt", "a") as file:
                file.write(mod_info.config.modName + mod_info.config.pluginExtension)

            with open(mo2ProfilePath + "modlist.txt", 'r') as file:
                filedata = file.read()
            markerString = "# This file was automatically generated by Mod Organizer."
            filedata = filedata.replace(markerString, markerString + "\n+" + junctionName)
            with open(mo2ProfilePath + "modlist.txt", 'w') as file:
                file.write(filedata)

            with open(mo2ProfilePath + "plugins.txt", "a") as file:
                file.write("*" + mod_info.config.modName + mod_info.config.pluginExtension)

            xEditName = ""
            match utils.Game(sys.argv[1]):
                case utils.Game.STARFIELD:
                    xEditName="SF1Edit"
                case utils.Game.FALLOUT4:
                    xEditName="FO4Edit"
                case utils.Game.SKYRIM:
                    xEditName="SSEEdit"
                case _:
                    print("CONFIGURATION ERROR")
            with open(mo2ProfilePath + "settings.ini", "a") as file:
                file.write("[custom_overwrites]\nxTranslator=" + junctionName + "\nCreation%20Kit=" + junctionName + "\n" + xEditName + "=" + junctionName)
    
    if len(sys.argv) > 3:
        notebookPath = sys.argv[3] + "/" + mod_info.config.game + "/" + mod_info.config.modName + "/"
        if not os.path.isdir(notebookPath):
            os.makedirs(notebookPath)  
            with open(notebookPath + "todo.md", "w") as file:
                file.write("#TODO")
            with open(notebookPath + "notes.md", "w") as file:
                file.write("") 

    if len(sys.argv) > 4:
        if sys.argv[4] == "True":
            voicesBasePath = "./Data/Sound/Voice/"
            voicesPath = voicesBasePath + mod_info.config.modName + ".esp"

            if mod_info.config.game == utils.Game.STARFIELD:
                os.makedirs(voicesPath)
                junction = voicesBasePath + mod_info.config.modName + ".esm"
                subprocess.run(f'mklink /J "{junction}" "{voicesPath}"', shell=True)
            else:  
                os.makedirs(voicesPath)
                if mod_info.config.modSize == utils.ModSize.SMALL:
                    junction = voicesBasePath + mod_info.config.modName + ".esl"
                    subprocess.run(f'mklink /J "{junction}" "{voicesPath}"', shell=True)

            with open("./Data/" + mod_info.config.modShortName + "_Voices.achlist" , "w") as file:
                file.write("[\n]") 
  
    if len(sys.argv) > 5:
        if sys.argv[5] == "True":
            with open("./Data/" + mod_info.config.modShortName + "_ModdedVoices.achlist" , "w") as file:
                file.write("[\n]") 

if __name__ == "__main__":
    main()